--- # required, replace with your own information -----
# _config.yml

title: Portfolio for Chicago resident and software developer
author: Ben Lopata
description: >
  my personal portfolio website
baseurl: "https://blopata.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
